### ISSUE TITLE
[MAF] maf-oncoplt Index Error

### ISSUE THREAD

**Issue by dmontielg** [sbslee/fuc#58]
HI,

I am trying to use the "maf-oncoplt" function with the example data found here: https://github.com/sbslee/fuc/blob/main/data/vcf/1.vcf

After converting the vcf using maf-vcf2maf I ran maf-oncoplt and gives the following error:

$ fuc maf-oncoplt out.maf out.pdf
IndexError: index 0 is out of bounds for axis 0 with size 0

Thank you,
Diego

**Comment by sbslee** [comment]
@dmontielg,

First off, thanks for your interest in using the `fuc` package!

The error is caused because the input VCF you used (`1.vcf`), and thus the input MAF as well (`out.maf`), does not have any functional annotation in it (e.g. `Missense_Mutation`). In order to draw an oncoplot, you need to first obtain functional annotation for each variant in input VCF from [Ensembl Variant Effect Predictor (VEP)](https://asia.ensembl.org/info/docs/tools/vep/index.html) or a similar annotation tool, and then convert the annotated VCF into a MAF file.

If you want to give the `maf-oncoplt` command a try, download the attached MAF file (`tcga_laml.maf.gz`) and run the following:

[tcga_laml.maf.gz](https://github.com/sbslee/fuc/files/8323499/tcga_laml.maf.gz)

```
$ fuc maf-oncoplt tcga_laml.maf.gz out.pdf
```

It should give you `out.pdf` that looks like this:

[out.pdf](https://github.com/sbslee/fuc/files/8323503/out.pdf)

Finally, are you bound to use CLI (command line interface) to draw oncoplots? If you are familiar with Python, I **highly** recommend that you use API (application programming interface) of [`fuc.pymaf`](https://sbslee-fuc.readthedocs.io/en/latest/api.html#module-fuc.api.pymaf) to draw oncoplots, which will give you way more control over how you draw oncoplots (e.g. addition of sample annotation tracks). You can find more information about using API to draw oncoplots: [here](https://sbslee-fuc.readthedocs.io/en/latest/api.html#fuc.api.pymaf.MafFrame.plot_oncoplot) and [here](https://sbslee-fuc.readthedocs.io/en/latest/tutorials.html#create-customized-oncoplots).

Feel free to ask any questions you might have.

**Comment by dmontielg** [comment]
HI,

Thank you so much for your quick reply! 
I found fuc very interesting/useful and want to give it a try.

I will try with the annotation now. Also, is it possible to add the sample_name to the oncoplot?

**Comment by sbslee** [comment]
> Also, is it possible to add the sample_name to the oncoplot?

Yes, but you need some extra work. Here's an example:

```
import matplotlib.pyplot as plt
from fuc import common, pymaf
common.load_dataset('tcga-laml')
maf_file = '~/fuc-data/tcga-laml/tcga_laml.maf.gz'
mf = pymaf.MafFrame.from_file(maf_file)
fig, ax = plt.subplots(figsize=(30, 7))
mf.plot_waterfall(linewidths=0.5, ax=ax)
samples = mf.matrix_waterfall().columns.to_list()
ax.set_xticks([x + 0.5 for x in range(len(samples))])
ax.set_xticklabels(samples, rotation=90, ha='center')
plt.tight_layout()
plt.savefig('out.png')
```

![out](https://user-images.githubusercontent.com/21111749/159471255-aa2dc6b7-4599-465d-b2ba-e4a273b63009.png)

As you can see above, addition of sample names to an oncoplot can be sometimes tricky especially if you have many samples to display. That is why `fuc.pymaf` does not display sample names by defaults.
