### ISSUE TITLE
matplotlib 3.9.0 deprecation

### ISSUE THREAD

**Issue by theAeon** [sbslee/fuc#71]
Looks like api/common.py imports BrokenBarHCollection from matplotlib.collections. This was [removed ](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#miscellaneous-removals)in the last matplotlib release.  Should be an easy swap to fill_between if their release notes page is to be believed.

**Comment by sbslee** [comment]
@theAeon,

Thank you for reporting the issue. Contrary to the release notes, simple swapping did not work. This issue is actually a critical one since it makes the entire `fuc` package incompatible with the latest `matplotlib` package.

I currently don't have the capacity to fix the problem, so I will deprecate the `common.plot_cytobands` method starting with the `0.38.0` release, especially since it was not used by many people anyway.
